### ISSUE TITLE
Junk Pickup

### ISSUE THREAD

**Issue by mgottholsen** [LouisvilleMetro/IFTTT-Smart-Louisville#10]
See https://api.louisvilleky.gov/api/geo/FindQuickServiceLookup?address=121%20FREEMAN%20AVE&city=Louisville

**Comment by mgottholsen** [comment]
This API is going to be deprecated. Might need to move the schedule to Open Data portal and query it that way instead.

**Comment by mattgantner** [comment]
There are several issues we will have to determine how to resolve to make this work. 
 
How dow users input their address - or is a geofence acceptable? Users away from home will not get alerts when using a geofence. Users with multiple properties will not get all alerts. 
How can we control notification frequency if a geofence is used?
How will edge cases work where a user borders two or more regions?
Can Lojic support the additional load IFTTT might bring?
This appears to be a many-to-one problem and without IDing users this will be difficult.

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/IFTTT-Smart-Louisville#15
