### ISSUE TITLE
Monthly Restaurant Inspection Report

### ISSUE THREAD

**Issue by mgottholsen** [LouisvilleMetro/IFTTT-Smart-Louisville#13]
See this article.
www.bizjournals.com/louisville/news/2017/04/12/these-louisville-restaurants-had-critical-food.html

Now, automate it.

**Comment by mgottholsen** [comment]
@jorgefelico You up for tackling this one?

**Comment by jorgefelico** [comment]
Sure am!

**Comment by mgottholsen** [comment]
See also [https://github.com/LouisvilleMetro/IFTTT-Smart-Louisville/issues/11](url)

**Comment by mgottholsen** [comment]
## New Feature Description:
As an IFTTT user, I want to receive a time-based (daily, weekly, monthly, quarterly) digest of critical food code violations.

## Template - 
Restaurant Name, Address
Grade
Inspection Result (bulleted list)

**Comment by jorgefelico** [comment]
@mgottholsen I'm working on this issue and noticed that our open data for the inspections does not have the inspection result as a list. We only have the score and grade. Here's a sample of one entry:
```json
EstablishmentID: "27867",
InspectionID: "1320961",
EstablishmentName: "FUNNEL CAKE #5",
PlaceName: " ",
Address: "MOBILE UNIT",
Address2: null,
City: "LOUISVILLE",
State: "KY",
Zip: "40202",
TypeDescription: "SELF-CONTAINED MOBILE FOOD UNITS",
Latitude: "38.2527",
Longitude	: "-85.7585",
InspectionDate: "2017-09-03 00:00:00",
Score: "93",
Grade: "C",
NameSearch: "FUNNELCAKE",
Intersection: null
```
So, my proposal
### Template
Restaurant Name, Address
Grade
Score

**Comment by mgottholsen** [comment]
There are a couple of different datasets that contain this information, but would require additional leg work.

We could pull just from Restaurant Inspection Scores. Or we could pull a query from the open data site that joins the following:

https://data.louisvilleky.gov/dataset/inspections
https://data.louisvilleky.gov/dataset/establishments

Or even:

https://data.louisvilleky.gov/dataset/yelp-data (the preview on this one does not automatically update, but the file download does. Or we could pull the files from S3)

Thoughts?

**Comment by mgottholsen** [comment]
Also, check out some of the other datasets https://data.louisvilleky.gov/group/health-wellness

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/IFTTT-Smart-Louisville#13
