### ISSUE TITLE
EMA Integration is missing data

### ISSUE THREAD

**Issue by mgottholsen** [LouisvilleMetro/IFTTT-Smart-Louisville#18]
The array that is processed by the EMA Controller is offset and does not pass data to the IFTTT API properly.

**Comment by mgottholsen** [comment]
Worked with team to replicate, unable to find the root cause of this issue. Going to get test credentials from GetRave and try issuing a test alert on channel2.

**Comment by jorgefelico** [comment]
@mgottholsen Any updates on this?

**Comment by mgottholsen** [comment]
I was able to get into the GetRave panel, so I can now issue test alerts. We can coordinate a time to do some testing, or I can see if we can get a login created for you all.

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/IFTTT-Smart-Louisville#8
