### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by mgottholsen** [LouisvilleMetro/IFTTT-Smart-Louisville#19]
Abstract tokens & keys to single config file. Throughout the project there are several services that utilizes unique keys etc. It would be nice to have them all in one place, with the ability to switch between dev & prod environment variables.

**Comment by ColWayne** [comment]
Moved the config file outside of the site dir added array to store keys etc. Pushed new branch out.  Needs to be tested.

**Comment by mgottholsen** [comment]
![image](https://user-images.githubusercontent.com/11966842/32788429-2a8178c0-c927-11e7-9244-21039104078f.png)

No, not really. Don't do that.

Feel free to deploy to the api.smartlouisville server. I'll get your credentials setup right now.

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/IFTTT-Smart-Louisville#7
