### ISSUE TITLE
Louisville Metro Government Notification

### ISSUE THREAD

**Issue by mgottholsen** [LouisvilleMetro/IFTTT-Smart-Louisville#28]
If Louisville Metro Government has a notification push to IFTTT trigger.

**Comment by mattgantner** [comment]
There is an inkling of a plan to build a centralized api to accept requests for notifications and then distribute those notifications through various channels, email, text, ifft, Alexa, Google home, push, etc. as new technologies arise the service can be extended without need to reimplement the initial request.

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/IFTTT-Smart-Louisville#1
