### ISSUE TITLE
Road Alerts integration

### ISSUE THREAD

**Issue by mgottholsen** [LouisvilleMetro/IFTTT-Smart-Louisville#5]
Harvest custom Alerts etc from Official Waze CCP endpoint.

**Comment by mgottholsen** [comment]
Hey @schnuerle, do you think you could integrate your Waze alert code for this issue?

**Comment by schnuerle** [comment]
Add my current code to this new repo: https://github.com/LouisvilleMetro/Waze-to-RSS/

**Comment by mgottholsen** [comment]
I'm not sure the best way to approach this, perhaps just exposing all of the Louisville road events that occur, and then use filtering code in the IFTTT applet builder to limit it to a certain area? This will require more investigation.

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/IFTTT-Smart-Louisville#20
