### ISSUE TITLE
LGE Current Outages - Get notification if LGE detect a power outage in my area

### ISSUE THREAD

**Issue by mgottholsen** [LouisvilleMetro/IFTTT-Smart-Louisville#7]

**Comment by brianherbert** [comment]
Is there a more accessible data source for this? I pulled this out of the console but it doesn't look reliable: http://stormcenter.lge-ku.com/data/interval_generation_data/2017_06_28_13_41_55/outages/0320003120002.js?timestamp=1498672599659

**Comment by mgottholsen** [comment]
Not that I'm aware of, I  have an email out to a security engineer @ LGE to see if he can assist.

**Comment by mgottholsen** [comment]
Outage by ZIP:
http://stormcenter.lge-ku.com/data/interval_generation_data/2017_10_31_13_27_26/report2.js?timestamp=1509471194225

Outage by County:
http://stormcenter.lge-ku.com/data/interval_generation_data/2017_10_31_13_27_26/report.js?timestamp=1509471194225

Totals:
http://stormcenter.lge-ku.com/data/interval_generation_data/2017_10_31_13_32_26/data.js?timestamp=1509471203384

Alerts:
http://stormcenter.lge-ku.com/data/alerts/2017_10_31_13_32_26/alerts.xml?timestamp=1509471203446

**Comment by mgottholsen** [comment]
"timestamp" appears to be unix epoch time?

**Comment by mgottholsen** [comment]
This issue was moved to office-of-civic-innovation/IFTTT-Smart-Louisville#18
